name: Create new Maven Release

on:
  workflow_call:
    inputs:
        with-submodules:
          description: "Clone repository with its submodules"
          type: boolean
          required: false
          default: false
    secrets:
      PAT:
        required: true

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'
          
  build:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: "Create new Release"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: ${{ inputs.with-submodules }}
        persist-credentials: false

    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven'

    - name: Configure GIT
      shell: bash
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: New Release
      shell: bash
      run: |
        mvn -B release:prepare -DpushChanges=false -Dgoals=deploy 
        mvn -B release:clean
        
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        # See https://github.com/orgs/community/discussions/25702 and https://github.com/orgs/community/discussions/26220
        github_token: ${{ secrets.PAT }}
        branch: ${{ github.ref }}
        tags: true
